### ISSUE TITLE
Data for running the Real experiment

### ISSUE THREAD

**Issue by mmontazeri2001** [tahaceritli/mIOHMM#1]
Hello,
There is no data in the data folder (either processed or raw) and I am not sure what structure should the data looks like for the preprocess function. Could you please at least upload the structure of Real data that your script need for running?
Thanks

**Comment by tahaceritli** [comment]
Hi,

To access the raw data, you would have to obtain access via https://www.ppmi-info.org/.

We obtained processed/data_for_PIOHMM.pkl following the process in https://github.com/kseverso/Discovery-of-PD-States-using-ML/. The notebook at https://github.com/kseverso/Discovery-of-PD-States-using-ML/blob/main/LD_Data_Processing.ipynb can be a good starting point. 

The x variable is a tensor of (338, 37, 59) where 338 denotes the number of patients, 37 is the number of timesteps and 59 is the number of features. Similarly. the d variable is a matrix of (338, 37). Hope this helps.

Best,
Taha
